package kfq.springcoco.entity;

public enum SkillEnum {
    REACTJS, VUEJS, ANGULAR, SVELTE, REDUX, GRAPHQL, VUEX, MOBX, NEXTJS, STORYBOOK, EMOTION, TAILWIND,
    NODEJS, SPRINGBOOT, SPRING, NESTJS, EXPRESSJS, DJANGO, FLASK, FASTAPI, RABBITMQ, HIBERNATE, MYBATIS,
    DOCKER, KUBERNETES, HELM, GITHUBACTION, JENKINS, ARGOCD, AZUREDEVOPS
}
